package com.hashedin.virtualproperty.application.service;

import com.github.javafaker.Faker;
import com.hashedin.virtualproperty.application.entities.Property;
import com.hashedin.virtualproperty.application.entities.PropertyImage;
import com.hashedin.virtualproperty.application.entities.User;
import com.hashedin.virtualproperty.application.exceptions.CustomException;
import com.hashedin.virtualproperty.application.repository.PropertyImageRepository;
import com.hashedin.virtualproperty.application.repository.PropertyRepo;
import com.hashedin.virtualproperty.application.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.util.*;

@Service
public class DbSeedService {

  @Autowired UserRepository userRepository;
  @Autowired PropertyRepo propertyRepo;
  @Autowired PropertyImageRepository propertyImageRepository;

  public void seedDatabase() {
    // disable seeding on production
    String currentUrl = ServletUriComponentsBuilder.fromCurrentContextPath().build().toUriString();
    if(!currentUrl.startsWith("http://localhost")){
      throw new CustomException("Please don't run seed on production server");
    }
    Faker faker = new Faker(new Locale("en-IND"));
    // create 100 fake users
    ArrayList<User> users = new ArrayList<User>();
    userRepository.deleteAll();
    int idCounter = 0;
    String[] images = this.getImageUrl();
    for (int i = 0; i < 100; i++) {
      try {
        String email = faker.internet().safeEmailAddress();
        String password = faker.bothify("???###?#?#");
        String address = faker.address().fullAddress();
        String name = faker.name().fullName();
        String mobile = faker.numerify("9#########");
        User user = new User(email, password, name, mobile, address);
        users.add(user);
        System.out.println(i + 1 + " " + user);
      } catch (Exception e) {
        i--;
      }
      this.userRepository.saveAll(users);
    }
    System.out.println("Users Created");

    // create 10 Properties for each city
    String[] states = this.getStates();
    System.out.println("DELETING STUFF");
//    propertyRepo.deleteAll();
    System.out.println("CREATING PROPERTIES");
    for (int i = 0; i < states.length; i++) {
      String state = states[i];
      String[] cities = this.getCities(state);
      System.out.println("State " + (i + 1) + " out of " + states.length);
      for (String city : cities) {
        List<Property> properties = new ArrayList<Property>();
        String[] types = new String[] {"Home", "Office", "Apartment"};
        int propertyCount = faker.number().numberBetween(5, 15);
        // add random properties between 5 to 15 for each city
        for (int k = 0; k < propertyCount; k++) {
          String type = types[faker.number().numberBetween(0, 2)];
          String purpose = faker.number().randomDigit() % 2 == 0 ? "Sell" : "Rent";
          String email = users.get(faker.number().numberBetween(0, users.size() - 1)).getEmail();
          int bedrooms = faker.number().numberBetween(1, 6);
          int bathrooms = faker.number().numberBetween(1, bedrooms);
          int bhk = faker.number().numberBetween(bedrooms, bedrooms + 2);
          String virtualTourURL=null;
          boolean virtualTour=false;
          Property p =
              new Property(
                  city,
                  state,
                  faker.address().streetAddress(),
                  type,
                  purpose,
                  faker.lorem().sentence(),
                  faker.number().numberBetween(500, 4000),
                  bhk,
                  faker.number().numberBetween(1990, 2021),
                  faker.number().numberBetween(500000, 50000000),
                  faker.number().numberBetween(1, 4),
                  bedrooms,
                  bathrooms,
                  Integer.parseInt(faker.address().zipCode()), virtualTourURL,virtualTour);
          p.setOwnerEmail(email);
          properties.add(p);
        }
        Iterable<Property> savedProperties = this.propertyRepo.saveAll(properties);
        ArrayList<PropertyImage> imagesToBeSaved = new ArrayList<>();
        for (Property property : savedProperties) {
          int imagesInProperty = faker.number().numberBetween(3, images.length - 1);
          TreeMap<Integer, Boolean> addedImages = new TreeMap<Integer, Boolean>();
          for (int k = 0; k < imagesInProperty; k++) {
            Integer imageIndex = faker.number().numberBetween(0, images.length - 1);
            if (addedImages.containsKey(imageIndex)) {
              k--;
            } else {
              addedImages.put(imageIndex, true);
              imagesToBeSaved.add(new PropertyImage("IMAGE" + idCounter++, images[imageIndex], "Naam", property));
            }
          }
        }
        this.propertyImageRepository.saveAll(imagesToBeSaved);
      }
    }
  }

  private String[] getStates() {
    Object[] keys = this.getStateCityHashMap().keySet().toArray();
    String[] res = new String[keys.length];
    for (int i = 0; i < keys.length; i++) {
      res[i] = keys[i].toString();
    }
    return res;
  }

  private String[] getCities(String state) {
    return this.getStateCityHashMap().get(state);
  }

  private String[] getImageUrl() {
    return new String[] {
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1602941525436-839a5be074ff?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1600585152915-d208bec867a1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1935&q=80",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1472224371017-08207f84aaae?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1797&q=80",
      "https://images.unsplash.com/photo-1613553483056-c8cb4c5d2a7b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"
    };
  }

  private HashMap<String, String[]> getStateCityHashMap() {
    HashMap<String, String[]> map = new HashMap<String, String[]>();
    map.put("Andaman and Nicobar Islands", new String[] {"Port Blair"});
    map.put(
        "Andhra Pradesh",
        new String[] {
          "Adoni",
          "Amalapuram",
          "Anakapalle",
          "Anantapur",
          "Bapatla",
          "Bheemunipatnam",
          "Bhimavaram",
          "Bobbili",
          "Chilakaluripet",
          "Chirala",
          "Chittoor",
          "Dharmavaram",
          "Eluru",
          "Gooty",
          "Gudivada",
          "Gudur",
          "Guntakal",
          "Guntur",
          "Hindupur",
          "Jaggaiahpet",
          "Jammalamadugu",
          "Kadapa",
          "Kadiri",
          "Kakinada",
          "Kandukur",
          "Kavali",
          "Kovvur",
          "Kurnool",
          "Macherla",
          "Machilipatnam",
          "Madanapalle",
          "Mandapeta",
          "Markapur",
          "Nagari",
          "Naidupet",
          "Nandyal",
          "Narasapuram",
          "Narasaraopet",
          "Narsipatnam",
          "Nellore",
          "Nidadavole",
          "Nuzvid",
          "Ongole",
          "Palacole",
          "Palasa Kasibugga",
          "Parvathipuram",
          "Pedana",
          "Peddapuram",
          "Pithapuram",
          "Ponnur",
          "Proddatur",
          "Punganur",
          "Puttur",
          "Rajahmundry",
          "Rajam",
          "Rajampet",
          "Ramachandrapuram",
          "Rayachoti",
          "Rayadurg",
          "Renigunta",
          "Repalle",
          "Salur",
          "Samalkot",
          "Sattenapalle",
          "Srikakulam",
          "Srikalahasti",
          "Srisailam Project (Right Flank Colony) Township",
          "Sullurpeta",
          "Tadepalligudem",
          "Tadpatri",
          "Tanuku",
          "Tenali",
          "Tirupati",
          "Tiruvuru",
          "Tuni",
          "Uravakonda",
          "Venkatagiri",
          "Vijayawada",
          "Vinukonda",
          "Visakhapatnam",
          "Vizianagaram",
          "Yemmiganur",
          "Yerraguntla"
        });
    map.put("Arunachal Pradesh", new String[] {"Naharlagun", "Pasighat"});
    map.put(
        "Assam",
        new String[] {
          "Barpeta",
          "Bongaigaon City",
          "Dhubri",
          "Dibrugarh",
          "Diphu",
          "Goalpara",
          "Guwahati",
          "Jorhat",
          "Karimganj",
          "Lanka",
          "Lumding",
          "Mangaldoi",
          "Mankachar",
          "Margherita",
          "Mariani",
          "Marigaon",
          "Nagaon",
          "Nalbari",
          "North Lakhimpur",
          "Rangia",
          "Sibsagar",
          "Silapathar",
          "Silchar",
          "Tezpur",
          "Tinsukia"
        });
    map.put(
        "Bihar",
        new String[] {
          "Araria",
          "Arrah",
          "Arwal",
          "Asarganj",
          "Aurangabad",
          "Bagaha",
          "Barh",
          "Begusarai",
          "Bettiah",
          "Bhabua",
          "Bhagalpur",
          "Buxar",
          "Chhapra",
          "Darbhanga",
          "Dehri-on-Sone",
          "Dumraon",
          "Forbesganj",
          "Gaya",
          "Gopalganj",
          "Hajipur",
          "Jamalpur",
          "Jamui",
          "Jehanabad",
          "Katihar",
          "Kishanganj",
          "Lakhisarai",
          "Lalganj",
          "Madhepura",
          "Madhubani",
          "Maharajganj",
          "Mahnar Bazar",
          "Makhdumpur",
          "Maner",
          "Manihari",
          "Marhaura",
          "Masaurhi",
          "Mirganj",
          "Mokameh",
          "Motihari",
          "Motipur",
          "Munger",
          "Murliganj",
          "Muzaffarpur",
          "Narkatiaganj",
          "Naugachhia",
          "Nawada",
          "Nokha",
          "Patna",
          "Piro",
          "Purnia",
          "Rafiganj",
          "Rajgir",
          "Ramnagar",
          "Raxaul Bazar",
          "Revelganj",
          "Rosera",
          "Saharsa",
          "Samastipur",
          "Sasaram",
          "Sheikhpura",
          "Sheohar",
          "Sherghati",
          "Silao",
          "Sitamarhi",
          "Siwan",
          "Sonepur",
          "Sugauli",
          "Sultanganj",
          "Supaul",
          "Warisaliganj"
        });
    map.put("Chandigarh", new String[] {"Chandigarh"});
    map.put(
        "Chhattisgarh",
        new String[] {
          "Ambikapur",
          "Bhatapara",
          "Bhilai Nagar",
          "Bilaspur",
          "Chirmiri",
          "Dalli-Rajhara",
          "Dhamtari",
          "Durg",
          "Jagdalpur",
          "Korba",
          "Mahasamund",
          "Manendragarh",
          "Mungeli",
          "Naila Janjgir",
          "Raigarh",
          "Raipur",
          "Rajnandgaon",
          "Sakti",
          "Tilda Newra"
        });
    map.put("Dadra and Nagar Haveli", new String[] {"Silvassa"});
    map.put("Delhi", new String[] {"Delhi", "New Delhi"});
    map.put("Goa", new String[] {"Mapusa", "Margao", "Marmagao", "Panaji"});
    map.put(
        "Gujarat",
        new String[] {
          "Adalaj",
          "Ahmedabad",
          "Amreli",
          "Anand",
          "Anjar",
          "Ankleshwar",
          "Bharuch",
          "Bhavnagar",
          "Bhuj",
          "Chhapra",
          "Deesa",
          "Dhoraji",
          "Godhra",
          "Jamnagar",
          "Kadi",
          "Kapadvanj",
          "Keshod",
          "Khambhat",
          "Lathi",
          "Limbdi",
          "Lunawada",
          "Mahesana",
          "Mahuva",
          "Manavadar",
          "Mandvi",
          "Mangrol",
          "Mansa",
          "Mahemdabad",
          "Modasa",
          "Morvi",
          "Nadiad",
          "Navsari",
          "Padra",
          "Palanpur",
          "Palitana",
          "Pardi",
          "Patan",
          "Petlad",
          "Porbandar",
          "Radhanpur",
          "Rajkot",
          "Rajpipla",
          "Rajula",
          "Ranavav",
          "Rapar",
          "Salaya",
          "Sanand",
          "Savarkundla",
          "Sidhpur",
          "Sihor",
          "Songadh",
          "Surat",
          "Talaja",
          "Thangadh",
          "Tharad",
          "Umbergaon",
          "Umreth",
          "Una",
          "Unjha",
          "Upleta",
          "Vadnagar",
          "Vadodara",
          "Valsad",
          "Vapi",
          "Vapi",
          "Veraval",
          "Vijapur",
          "Viramgam",
          "Visnagar",
          "Vyara",
          "Wadhwan",
          "Wankaner"
        });
    map.put(
        "Haryana",
        new String[] {
          "Bahadurgarh",
          "Bhiwani",
          "Charkhi Dadri",
          "Faridabad",
          "Fatehabad",
          "Gohana",
          "Gurgaon",
          "Hansi",
          "Hisar",
          "Jind",
          "Kaithal",
          "Karnal",
          "Ladwa",
          "Mahendragarh",
          "Mandi Dabwali",
          "Narnaul",
          "Narwana",
          "Palwal",
          "Panchkula",
          "Panipat",
          "Pehowa",
          "Pinjore",
          "Rania",
          "Ratia",
          "Rewari",
          "Rohtak",
          "Safidon",
          "Samalkha",
          "Sarsod",
          "Shahbad",
          "Sirsa",
          "Sohna",
          "Sonipat",
          "Taraori",
          "Thanesar",
          "Tohana",
          "Yamunanagar"
        });
    map.put(
        "Himachal Pradesh",
        new String[] {"Mandi", "Nahan", "Palampur", "Shimla", "Solan", "Sundarnagar"});
    map.put(
        "Jammu and Kashmir",
        new String[] {
          "Anantnag",
          "Baramula",
          "Jammu",
          "Kathua",
          "Punch",
          "Rajauri",
          "Sopore",
          "Srinagar",
          "Udhampur"
        });
    map.put(
        "Jharkhand",
        new String[] {
          "Adityapur",
          "Bokaro Steel City",
          "Chaibasa",
          "Chatra",
          "Chirkunda",
          "Medininagar (Daltonganj)",
          "Deoghar",
          "Dhanbad",
          "Dumka",
          "Giridih",
          "Gumia",
          "Hazaribag",
          "Jamshedpur",
          "Jhumri Tilaiya",
          "Lohardaga",
          "Madhupur",
          "Mihijam",
          "Musabani",
          "Pakaur",
          "Patratu",
          "Phusro",
          "Ramgarh",
          "Ranchi",
          "Sahibganj",
          "Saunda",
          "Simdega",
          "Tenu dam-cum-Kathhara"
        });
    map.put(
        "Karnataka",
        new String[] {
          "Adyar",
          "Afzalpur",
          "Arsikere",
          "Athni",
          "Bengaluru",
          "Belagavi",
          "Ballari",
          "Chikkamagaluru",
          "Davanagere",
          "Gokak",
          "Hubli-Dharwad",
          "Karwar",
          "Kolar",
          "Lakshmeshwar",
          "Lingsugur",
          "Maddur",
          "Madhugiri",
          "Madikeri",
          "Magadi",
          "Mahalingapura",
          "Malavalli",
          "Malur",
          "Mandya",
          "Mangaluru",
          "Manvi",
          "Mudalagi",
          "Mudabidri",
          "Muddebihal",
          "Mudhol",
          "Mulbagal",
          "Mundargi",
          "Mysore",
          "Nanjangud",
          "Nargund",
          "Navalgund",
          "Nelamangala",
          "Pavagada",
          "Piriyapatna",
          "Puttur",
          "Rabkavi Banhatti",
          "Raayachuru",
          "Ranebennuru",
          "Ramanagaram",
          "Ramdurg",
          "Ranibennur",
          "Robertson Pet",
          "Ron",
          "Sadalagi",
          "Sagara",
          "Sakaleshapura",
          "Sindagi",
          "Sanduru",
          "Sankeshwara",
          "Saundatti-Yellamma",
          "Savanur",
          "Sedam",
          "Shahabad",
          "Shahpur",
          "Shiggaon",
          "Shikaripur",
          "Shivamogga",
          "Surapura",
          "Shrirangapattana",
          "Sidlaghatta",
          "Sindhagi",
          "Sindhnur",
          "Sira",
          "Sirsi",
          "Siruguppa",
          "Srinivaspur",
          "Tarikere",
          "Tekkalakote",
          "Terdal",
          "Talikota",
          "Tiptur",
          "Tumkur",
          "Udupi",
          "Vijayapura",
          "Wadi",
          "Yadgir"
        });
    map.put(
        "Kerala",
        new String[] {
          "Adoor",
          "Alappuzha",
          "Attingal",
          "Chalakudy",
          "Changanassery",
          "Cherthala",
          "Chittur-Thathamangalam",
          "Guruvayoor",
          "Kanhangad",
          "Kannur",
          "Kasaragod",
          "Kayamkulam",
          "Kochi",
          "Kodungallur",
          "Kollam",
          "Kottayam",
          "Kozhikode",
          "Kunnamkulam",
          "Malappuram",
          "Mattannur",
          "Mavelikkara",
          "Mavoor",
          "Muvattupuzha",
          "Nedumangad",
          "Neyyattinkara",
          "Nilambur",
          "Ottappalam",
          "Palai",
          "Palakkad",
          "Panamattom",
          "Panniyannur",
          "Pappinisseri",
          "Paravoor",
          "Pathanamthitta",
          "Peringathur",
          "Perinthalmanna",
          "Perumbavoor",
          "Ponnani",
          "Punalur",
          "Puthuppally",
          "Koyilandy",
          "Shoranur",
          "Taliparamba",
          "Thiruvalla",
          "Thiruvananthapuram",
          "Thodupuzha",
          "Thrissur",
          "Tirur",
          "Vaikom",
          "Varkala",
          "Vatakara"
        });
    map.put(
        "Madhya Pradesh",
        new String[] {
          "Alirajpur",
          "Ashok Nagar",
          "Balaghat",
          "Bhopal",
          "Ganjbasoda",
          "Gwalior",
          "Indore",
          "Itarsi",
          "Jabalpur",
          "Lahar",
          "Maharajpur",
          "Mahidpur",
          "Maihar",
          "Malaj Khand",
          "Manasa",
          "Manawar",
          "Mandideep",
          "Mandla",
          "Mandsaur",
          "Mauganj",
          "Mhow Cantonment",
          "Mhowgaon",
          "Morena",
          "Multai",
          "Mundi",
          "Murwara (Katni)",
          "Nagda",
          "Nainpur",
          "Narsinghgarh",
          "Narsinghgarh",
          "Neemuch",
          "Nepanagar",
          "Niwari",
          "Nowgong",
          "Nowrozabad (Khodargama)",
          "Pachore",
          "Pali",
          "Panagar",
          "Pandhurna",
          "Panna",
          "Pasan",
          "Pipariya",
          "Pithampur",
          "Porsa",
          "Prithvipur",
          "Raghogarh-Vijaypur",
          "Rahatgarh",
          "Raisen",
          "Rajgarh",
          "Ratlam",
          "Rau",
          "Rehli",
          "Rewa",
          "Sabalgarh",
          "Sagar",
          "Sanawad",
          "Sarangpur",
          "Sarni",
          "Satna",
          "Sausar",
          "Sehore",
          "Sendhwa",
          "Seoni",
          "Seoni-Malwa",
          "Shahdol",
          "Shajapur",
          "Shamgarh",
          "Sheopur",
          "Shivpuri",
          "Shujalpur",
          "Sidhi",
          "Sihora",
          "Singrauli",
          "Sironj",
          "Sohagpur",
          "Tarana",
          "Tikamgarh",
          "Ujjain",
          "Umaria",
          "Vidisha",
          "Vijaypur",
          "Wara Seoni"
        });
    map.put(
        "Maharashtra",
        new String[] {
          "Ahmednagar",
          "Akola",
          "Akot",
          "Amalner",
          "Ambejogai",
          "Amravati",
          "Anjangaon",
          "Arvi",
          "Aurangabad",
          "Bhiwandi",
          "Dhule",
          "Kalyan-Dombivali",
          "Ichalkaranji",
          "Kalyan-Dombivali",
          "Karjat",
          "Latur",
          "Loha",
          "Lonar",
          "Lonavla",
          "Mahad",
          "Malegaon",
          "Malkapur",
          "Mangalvedhe",
          "Mangrulpir",
          "Manjlegaon",
          "Manmad",
          "Manwath",
          "Mehkar",
          "Mhaswad",
          "Mira-Bhayandar",
          "Morshi",
          "Mukhed",
          "Mul",
          "Greater Mumbai",
          "Murtijapur",
          "Nagpur",
          "Nanded-Waghala",
          "Nandgaon",
          "Nandura",
          "Nandurbar",
          "Narkhed",
          "Nashik",
          "Navi Mumbai",
          "Nawapur",
          "Nilanga",
          "Osmanabad",
          "Ozar",
          "Pachora",
          "Paithan",
          "Palghar",
          "Pandharkaoda",
          "Pandharpur",
          "Panvel",
          "Parbhani",
          "Parli",
          "Partur",
          "Pathardi",
          "Pathri",
          "Patur",
          "Pauni",
          "Pen",
          "Phaltan",
          "Pulgaon",
          "Pune",
          "Purna",
          "Pusad",
          "Rahuri",
          "Rajura",
          "Ramtek",
          "Ratnagiri",
          "Raver",
          "Risod",
          "Sailu",
          "Sangamner",
          "Sangli",
          "Sangole",
          "Sasvad",
          "Satana",
          "Satara",
          "Savner",
          "Sawantwadi",
          "Shahade",
          "Shegaon",
          "Shendurjana",
          "Shirdi",
          "Shirpur-Warwade",
          "Shirur",
          "Shrigonda",
          "Shrirampur",
          "Sillod",
          "Sinnar",
          "Solapur",
          "Soyagaon",
          "Talegaon Dabhade",
          "Talode",
          "Tasgaon",
          "Thane",
          "Tirora",
          "Tuljapur",
          "Tumsar",
          "Uchgaon",
          "Udgir",
          "Umarga",
          "Umarkhed",
          "Umred",
          "Uran",
          "Uran Islampur",
          "Vadgaon Kasba",
          "Vaijapur",
          "Vasai-Virar",
          "Vita",
          "Wadgaon Road",
          "Wai",
          "Wani",
          "Wardha",
          "Warora",
          "Warud",
          "Washim",
          "Yavatmal",
          "Yawal",
          "Yevla"
        });
    map.put("Manipur", new String[] {"Imphal", "Lilong", "Mayang Imphal", "Thoubal"});
    map.put("Meghalaya", new String[] {"Nongstoin", "Shillong", "Tura"});
    map.put("Mizoram", new String[] {"Aizawl", "Lunglei", "Saiha"});
    map.put(
        "Nagaland",
        new String[] {"Dimapur", "Kohima", "Mokokchung", "Tuensang", "Wokha", "Zunheboto"});
    map.put(
        "Odisha",
        new String[] {
          "Balangir",
          "Baleshwar Town",
          "Barbil",
          "Bargarh",
          "Baripada Town",
          "Bhadrak",
          "Bhawanipatna",
          "Bhubaneswar",
          "Brahmapur",
          "Byasanagar",
          "Cuttack",
          "Dhenkanal",
          "Jatani",
          "Jharsuguda",
          "Kendrapara",
          "Kendujhar",
          "Malkangiri",
          "Nabarangapur",
          "Paradip",
          "Parlakhemundi",
          "Pattamundai",
          "Phulabani",
          "Puri",
          "Rairangpur",
          "Rajagangapur",
          "Raurkela",
          "Rayagada",
          "Sambalpur",
          "Soro",
          "Sunabeda",
          "Sundargarh",
          "Talcher",
          "Tarbha",
          "Titlagarh"
        });
    map.put("Puducherry", new String[] {"Karaikal", "Mahe", "Pondicherry", "Yanam"});
    map.put(
        "Punjab",
        new String[] {
          "Amritsar",
          "Barnala",
          "Batala",
          "Bathinda",
          "Dhuri",
          "Faridkot",
          "Fazilka",
          "Firozpur",
          "Firozpur Cantt.",
          "Gobindgarh",
          "Gurdaspur",
          "Hoshiarpur",
          "Jagraon",
          "Jalandhar Cantt.",
          "Jalandhar",
          "Kapurthala",
          "Khanna",
          "Kharar",
          "Kot Kapura",
          "Longowal",
          "Ludhiana",
          "Malerkotla",
          "Malout",
          "Mansa",
          "Moga",
          "Mohali",
          "Morinda, India",
          "Mukerian",
          "Muktsar",
          "Nabha",
          "Nakodar",
          "Nangal",
          "Nawanshahr",
          "Pathankot",
          "Patiala",
          "Pattran",
          "Patti",
          "Phagwara",
          "Phillaur",
          "Qadian",
          "Raikot",
          "Rajpura",
          "Rampura Phul",
          "Rupnagar",
          "Samana",
          "Sangrur",
          "Sirhind Fatehgarh Sahib",
          "Sujanpur",
          "Sunam",
          "Talwara",
          "Tarn Taran",
          "Urmar Tanda",
          "Zira",
          "Zirakpur"
        });
    map.put(
        "Rajasthan",
        new String[] {
          "Ajmer",
          "Alwar",
          "Bikaner",
          "Bharatpur",
          "Bhilwara",
          "Jaipur",
          "Jodhpur",
          "Lachhmangarh",
          "Ladnu",
          "Lakheri",
          "Lalsot",
          "Losal",
          "Makrana",
          "Malpura",
          "Mandalgarh",
          "Mandawa",
          "Mangrol",
          "Merta City",
          "Mount Abu",
          "Nadbai",
          "Nagar",
          "Nagaur",
          "Nasirabad",
          "Nathdwara",
          "Neem-Ka-Thana",
          "Nimbahera",
          "Nohar",
          "Nokha",
          "Pali",
          "Phalodi",
          "Phulera",
          "Pilani",
          "Pilibanga",
          "Pindwara",
          "Pipar City",
          "Prantij",
          "Pratapgarh",
          "Raisinghnagar",
          "Rajakhera",
          "Rajaldesar",
          "Rajgarh (Alwar)",
          "Rajgarh (Churu)",
          "Rajsamand",
          "Ramganj Mandi",
          "Ramngarh",
          "Ratangarh",
          "Rawatbhata",
          "Rawatsar",
          "Reengus",
          "Sadri",
          "Sadulshahar",
          "Sadulpur",
          "Sagwara",
          "Sambhar",
          "Sanchore",
          "Sangaria",
          "Sardarshahar",
          "Sawai Madhopur",
          "Shahpura",
          "Shahpura",
          "Sheoganj",
          "Sikar",
          "Sirohi",
          "Sojat",
          "Sri Madhopur",
          "Sujangarh",
          "Sumerpur",
          "Suratgarh",
          "Taranagar",
          "Todabhim",
          "Todaraisingh",
          "Tonk",
          "Udaipur",
          "Udaipurwati",
          "Vijainagar, Ajmer"
        });
    map.put(
        "Tamil Nadu",
        new String[] {
          "Arakkonam",
          "Aruppukkottai",
          "Chennai",
          "Coimbatore",
          "Erode",
          "Gobichettipalayam",
          "Kancheepuram",
          "Karur",
          "Lalgudi",
          "Madurai",
          "Manachanallur",
          "Nagapattinam",
          "Nagercoil",
          "Namagiripettai",
          "Namakkal",
          "Nandivaram-Guduvancheri",
          "Nanjikottai",
          "Natham",
          "Nellikuppam",
          "Neyveli (TS)",
          "O' Valley",
          "Oddanchatram",
          "P.N.Patti",
          "Pacode",
          "Padmanabhapuram",
          "Palani",
          "Palladam",
          "Pallapatti",
          "Pallikonda",
          "Panagudi",
          "Panruti",
          "Paramakudi",
          "Parangipettai",
          "Pattukkottai",
          "Perambalur",
          "Peravurani",
          "Periyakulam",
          "Periyasemur",
          "Pernampattu",
          "Pollachi",
          "Polur",
          "Ponneri",
          "Pudukkottai",
          "Pudupattinam",
          "Puliyankudi",
          "Punjaipugalur",
          "Ranipet",
          "Rajapalayam",
          "Ramanathapuram",
          "Rameshwaram",
          "Rasipuram",
          "Salem",
          "Sankarankoil",
          "Sankari",
          "Sathyamangalam",
          "Sattur",
          "Shenkottai",
          "Sholavandan",
          "Sholingur",
          "Sirkali",
          "Sivaganga",
          "Sivagiri",
          "Sivakasi",
          "Srivilliputhur",
          "Surandai",
          "Suriyampalayam",
          "Tenkasi",
          "Thammampatti",
          "Thanjavur",
          "Tharamangalam",
          "Tharangambadi",
          "Theni Allinagaram",
          "Thirumangalam",
          "Thirupuvanam",
          "Thiruthuraipoondi",
          "Thiruvallur",
          "Thiruvarur",
          "Thuraiyur",
          "Tindivanam",
          "Tiruchendur",
          "Tiruchengode",
          "Tiruchirappalli",
          "Tirukalukundram",
          "Tirukkoyilur",
          "Tirunelveli",
          "Tirupathur",
          "Tirupathur",
          "Tiruppur",
          "Tiruttani",
          "Tiruvannamalai",
          "Tiruvethipuram",
          "Tittakudi",
          "Udhagamandalam",
          "Udumalaipettai",
          "Unnamalaikadai",
          "Usilampatti",
          "Uthamapalayam",
          "Uthiramerur",
          "Vadakkuvalliyur",
          "Vadalur",
          "Vadipatti",
          "Valparai",
          "Vandavasi",
          "Vaniyambadi",
          "Vedaranyam",
          "Vellakoil",
          "Vellore",
          "Vikramasingapuram",
          "Viluppuram",
          "Virudhachalam",
          "Virudhunagar",
          "Viswanatham"
        });
    map.put(
        "Telangana",
        new String[] {
          "Adilabad",
          "Bellampalle",
          "Bhadrachalam",
          "Bhainsa",
          "Bhongir",
          "Bodhan",
          "Farooqnagar",
          "Gadwal",
          "Hyderabad",
          "Jagtial",
          "Jangaon",
          "Kagaznagar",
          "Kamareddy",
          "Karimnagar",
          "Khammam",
          "Koratla",
          "Kothagudem",
          "Kyathampalle",
          "Mahbubnagar",
          "Mancherial",
          "Mandamarri",
          "Manuguru",
          "Medak",
          "Miryalaguda",
          "Nagarkurnool",
          "Narayanpet",
          "Nirmal",
          "Nizamabad",
          "Palwancha",
          "Ramagundam",
          "Sadasivpet",
          "Sangareddy",
          "Siddipet",
          "Sircilla",
          "Suryapet",
          "Tandur",
          "Vikarabad",
          "Wanaparthy",
          "Warangal",
          "Yellandu"
        });
    map.put(
        "Tripura",
        new String[] {
          "Agartala", "Belonia", "Dharmanagar", "Kailasahar", "Khowai", "Pratapgarh", "Udaipur"
        });
    map.put(
        "Uttar Pradesh",
        new String[] {
          "Achhnera",
          "Agra",
          "Aligarh",
          "Allahabad",
          "Amroha",
          "Azamgarh",
          "Bahraich",
          "Chandausi",
          "Etawah",
          "Firozabad",
          "Fatehpur Sikri",
          "Hapur",
          "Hardoi ",
          "Jhansi",
          "Kalpi",
          "Kanpur",
          "Khair",
          "Laharpur",
          "Lakhimpur",
          "Lal Gopalganj Nindaura",
          "Lalitpur",
          "Lalganj",
          "Lar",
          "Loni",
          "Lucknow",
          "Mathura",
          "Meerut",
          "Modinagar",
          "Moradabad",
          "Nagina",
          "Najibabad",
          "Nakur",
          "Nanpara",
          "Naraura",
          "Naugawan Sadat",
          "Nautanwa",
          "Nawabganj",
          "Nehtaur",
          "Niwai",
          "Noida",
          "Noorpur",
          "Obra",
          "Orai",
          "Padrauna",
          "Palia Kalan",
          "Parasi",
          "Phulpur",
          "Pihani",
          "Pilibhit",
          "Pilkhuwa",
          "Powayan",
          "Pukhrayan",
          "Puranpur",
          "Purquazi",
          "Purwa",
          "Rae Bareli",
          "Rampur",
          "Rampur Maniharan",
          "Rampur Maniharan",
          "Rasra",
          "Rath",
          "Renukoot",
          "Reoti",
          "Robertsganj",
          "Rudauli",
          "Rudrapur",
          "Sadabad",
          "Safipur",
          "Saharanpur",
          "Sahaspur",
          "Sahaswan",
          "Sahawar",
          "Sahjanwa",
          "Saidpur",
          "Sambhal",
          "Samdhan",
          "Samthar",
          "Sandi",
          "Sandila",
          "Sardhana",
          "Seohara",
          "Shahabad, Hardoi",
          "Shahabad, Rampur",
          "Shahganj",
          "Shahjahanpur",
          "Shamli",
          "Shamsabad, Agra",
          "Shamsabad, Farrukhabad",
          "Sherkot",
          "Shikarpur, Bulandshahr",
          "Shikohabad",
          "Shishgarh",
          "Siana",
          "Sikanderpur",
          "Sikandra Rao",
          "Sikandrabad",
          "Sirsaganj",
          "Sirsi",
          "Sitapur",
          "Soron",
          "Suar",
          "Sultanpur",
          "Sumerpur",
          "Tanda",
          "Thakurdwara",
          "Thana Bhawan",
          "Tilhar",
          "Tirwaganj",
          "Tulsipur",
          "Tundla",
          "Ujhani",
          "Unnao",
          "Utraula",
          "Varanasi",
          "Vrindavan",
          "Warhapur",
          "Zaidpur",
          "Zamania"
        });
    map.put(
        "Uttarakhand",
        new String[] {
          "Bageshwar",
          "Dehradun",
          "Haldwani-cum-Kathgodam",
          "Hardwar",
          "Kashipur",
          "Manglaur",
          "Mussoorie",
          "Nagla",
          "Nainital",
          "Pauri",
          "Pithoragarh",
          "Ramnagar",
          "Rishikesh",
          "Roorkee",
          "Rudrapur",
          "Sitarganj",
          "Srinagar",
          "Tehri"
        });
    map.put(
        "West Bengal",
        new String[] {
          "Adra",
          "Alipurduar",
          "Arambagh",
          "Asansol",
          "Baharampur",
          "Balurghat",
          "Bankura",
          "Darjiling",
          "English Bazar",
          "Gangarampur",
          "Habra",
          "Hugli-Chinsurah",
          "Jalpaiguri",
          "Jhargram",
          "Kalimpong",
          "Kharagpur",
          "Kolkata",
          "Mainaguri",
          "Malda",
          "Mathabhanga",
          "Medinipur",
          "Memari",
          "Monoharpur",
          "Murshidabad",
          "Nabadwip",
          "Naihati",
          "Panchla",
          "Pandua",
          "Paschim Punropara",
          "Purulia",
          "Raghunathpur",
          "Raghunathganj",
          "Raiganj",
          "Rampurhat",
          "Ranaghat",
          "Sainthia",
          "Santipur",
          "Siliguri",
          "Sonamukhi",
          "Srirampore",
          "Suri",
          "Taki",
          "Tamluk",
          "Tarakeswar"
        });
    return map;
  }
  ;
}
